package.json
=> build: release v1.12.0

package.json
=> build: release v1.13.0

package.json
=> build: release v1.14.0

package.json
=> build: release v1.15.0

package.json
=> build: release v1.16.0

src/po-theme-custom.css
build: atualizado variaveis do tema de acordo com @portinari/style
=> build: atualizado variaveis do tema de acordo com @portinari/style

package.json
=> build: release v1.17.0

package.json, src/po-theme-custom.css
=> build: release v1.19.0

package.json, src/po-theme-custom.css
=> build: release v1.20.0

package.json
=> build: release v1.21.0

package.json
=> build: release v1.22.2

package.json
=> build: release v1.22.3

package.json
=> build: release v1.23.0

package.json
=> build: release v1.24.0

package.json
=> build: release v1.25.0

package.json
=> build: release v1.26.0

package.json
=> build: release v1.27.1

package.json
=> build: release v1.28.0

package.json
=> build: release 2.0.0-beta.2

package.json
=> build: release 2.0.0-rc.1

src/po-theme-custom.css
=> fix(table): definidas variáveis para radio button

package.json
=> build: release v2.1.0

package.json
=> build: release v2.3.0

package.json
=> build: release v2.4.0

package.json
=> build: release v2.5.0

package.json
=> build: release v2.6.0

package.json
=> build: release v2.9.0

package.json
Correção da geração do pacote do tema
=> build: release v2.10.1

src/po-theme-custom.css
Novas cores para o nome do produto e da mensagem "boas-vindas".
Fixes DTHFUI-3709
=> feat(page-login): adiciona nova cor no cabeçalho

package.json
=> build: release v3.0.0-beta.1

src/po-theme-custom.css
Adiciona variáveis de cor para botão opcional de suporte adicionado ao template.
Fixes DTHFUI-3712
=> feat(page-login): adiciona variáveis para botão de suporte

package.json
=> build: release v3.3.0

package.json
=> build: release v3.4.0

.github/workflows/publish_ci.yml
**@totvs/po-theme**
DTHFUI-1780
- Adiciona no github actions uma ação para publicar o pacote de forma automatizada.
- Remove a tag dev do package.json, para a partir dali o pacote ser publicado utilizando a tag next e latest.
**Para testar:**
Para chegar em um teste mais próximo, pode ser utilizado o repositório: https://github.com/nicoleoliveira/po-theme-totvs-test-github-actions. Utilize esse repositório para subir as versões e executar as actions.
- Altere para uma nova versão nova no package.json
- Git commit e git push
- git tag <versão> git push origin <versão>
- abra a aba das actions e veja se está executando o fluxo de trabalho.
=> build(actions): cria ação de publicação do pacote

package.json
=> build: release v3.5.0

package.json, src/po-theme-custom.css
=> build: release v3.6.0

src/po-theme-custom.css
Adiciona a variável:
--color-popup-background-color-scrollbar
=> feat(popup): adiciona variavel do scrollbar

package.json
=> build: release v3.7.0

package.json
=> build: release v3.8.0

package.json, src/po-theme-custom.css
=> build: release v3.9.0

package.json
=> build: release v3.10.0

src/po-theme-custom.css
**Po-Chart**
**DTHFUI-1757**
Inclui as variáveis de cor para o PoChartType.Line.
=> feat(chart): inclui variáveis de cor para o PoChartType.Line

package.json
=> build: release v3.12.0

package.json
=> build: release v3.14.0

package.json
=> build: release v4.0.0

package.json
=> build: release v4.1.0

src/po-theme-custom.css
Inclui variáveis de cor do novo componente PO GAUGE
DTHFUI-4341
=> feat(gauge): inclui variáveis de cor do novo componente

package.json
=> build: release v4.2.0

package.json
=> build: release v4.4.0

package.json
=> build: release v4.6.0

package.json
=> build: release v4.7.0

package.json
=> build: release v4.8.0

package.json
=> build: release v4.9.0

package.json
=> build: release v4.10.0

package.json
=> build: release v4.10.1

package.json
=> build: release v4.11.0

package.json
=> build: release v4.12.0

package.json
=> build: release v4.13.0

package.json
=> build: release v4.14.0

package.json
=> build: release v4.15.0

package.json
=> build: release v4.16.1

src/po-theme-custom.css
=> feat(calendar): adiciona estilos para permitir modo range

package.json
=> build: release v5.0.0-rc.1

package.json
=> build: release v5.0.0

package.json
=> build: release v5.1.0

package.json
=> build: release v5.2.1

package.json
=> build: release v5.3.0

package.json
=> build: release v5.4.0

package.json
=> build: release v5.7.0

package.json
=> build: release v5.8.0

package.json
=> build: release v5.10.0

package.json
=> build: release v5.11.0

package.json
=> build: release v5.12.0

package.json
=> build: release v5.13.0

package.json
=> build: release v5.13.1

package.json
=> build: release v5.14.0

package.json
=>  build: release v5.15.0

package.json
=> build: release v5.17.0

package.json
=> build: release v5.20.0

package.json
=> build: release v5.21.0

package.json
=> build: release v5.22.0

package.json
=> build: release v5.22.1

src/po-theme-custom.css
remove estilo do po-chart-gauge
=> refactor(chart-gauge): remove estilo do po-chart-gauge

package.json
=> build: release v6.0.0-rc.1

package.json
=> build: release v6.0.0

package.json
=> build: release v6.1.0

package.json
=> build: release v5.22.3

package.json
=> build: release v6.2.0

package.json
=> build: release v5.22.4

package.json
=> build: release v6.5.0

package.json
=> build: release v5.22.5

package.json
=> build: release v6.6.0

package.json
=> build: release v5.22.7

src/po-theme-custom.css
Melhora acessibilidade e contraste do componente checkbox.
adiciona nova variável para a customização do background quando o checkbox está desabilitado e ativo
- color-checkbox-background-color-active-disabled
adiciona nova variável para a customização da cor do hover do checkbox
- color-checkbox-hover-active
fixes - DTHFUI-5841
=> feat(checkbox): melhora acessibilidade e contraste do componente

package.json
=> build: release v6.8.0

package.json
=> build: release v6.9.0

src/po-theme-custom.css
Aplicação de novo estilo definido pelo design system com remoção, alteração e inclusão de variáveis.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Variáveis adicionadas:
--color-secondary-light-40;
--color-danger-light-05;
--color-danger-light-20;
--color-outline-focused;
--color-button-box-shadow;
--color-button-border-color-link;
Variáveis removidas:
--color-button-color-primary-hover
--color-button-color-primary-pressed
--color-button-border-primary-disabled
=> feat(button): aplica estilo definido pelo design system

package.json
=> build: release v6.10.0

package.json
=> build: release v6.10.1

package.json
=> build: release v6.11.0

package.json
=> build: release v6.12.0

src/po-theme-custom.css
Cria componente interno de radio, seguindo as regras de estilo do AnimaliaDS
Fixes: DTHFUI-6067
=> feat(radio): cria novo componente po-radio

src/po-theme-custom.css
Permite a utilização do kind primary com a propriedade danger habilitada
Fixes DTHFUI-6002
=> feat(button): inclui estilo kind primary danger

package.json
=> build: release v6.13.0

package.json
=> build: release v6.13.1

package.json
=> build: release v14.0.0-next.0

src/po-theme-custom.css
inclui global e brand tokens e define variáveis padronizadas para alteração do estilo do botão
fixes: DTHFUI-6075
=> feat(button): inclui global e brand tokens

package.json, src/po-theme-custom.css
=> build: release v14.0.0

package.json
=> build: release v14.1.0

package.json
=> build: release v14.2.0

package.json
=> build: release v14.2.1

README.md, package.json
=> build: release v14.3.0

src/po-theme-custom.css
fix(loading): corrige cor do overlay no theme totvs
alterar no angular.json : 
```
"styles": [
"./node_modules/@totvs/po-theme/css/po-theme-default-variables.min.css",
"./node_modules/@totvs/po-theme/css/po-theme-default.min.css",
"./node_modules/@po-ui/style/css/po-theme-core.min.css",
"projects/app/src/styles.css"
],
```
=> fix(loading): corrige cor do overlay no theme totvs

package.json
=> build: release v14.3.1

src/po-theme-custom.css
Aplicação de novo estilo definido pelo design system.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Fixes DTHFUI-6352
=> feat(switch): aplica estilo definido pelo DS

package.json
=> build: release v14.4.0

src/po-theme-custom.css
Aplicação de novo estilo definido pelo design system.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Fixes DTHFUI-5861
=> feat(radiogroup): aplica estilo definido pelo DS

src/po-theme-custom.css
Inclui definições do design system nos seguintes componentes: po-input
po-url
po-password
po-number
po-multiselect
po-lookup
po-login
po-email
po-decimal
po-datepicker
po-datepicker-range
po-combo
fixes DTHFUI-6339
=> feat(fields): inclui definições do AnimaliaDS

src/po-theme-custom.css
Aplicação de novo estilo definido pelo design system.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Fixes DTHFUI-6443
=> feat(select): aplica estilo definido pelo DS

src/po-theme-custom.css
Aplica estilo definido pelo AnimaliaDS
Fixes DTHFUI-6442
=> feat(textarea): aplica estilo e acessibilidade definidos pelo DS

src/po-theme-custom.css
Aplica estilo definido pelo AnimaliaDS para o button group.
Fixes DTHFUI-6451
=> feat(button-group): aplica estilo definido pelo AnimaliaDS

package.json
=> build: release v14.6.0

src/po-theme-custom.css
Cria componente de link, seguindo as regras de estilo do AnimaliaDS.
Fixes: DTHFUI-6508
=> feat(link): cria novo componente po-link

package.json
=> build: release v14.7.0

package.json
=> build: release 14.7.1

src/po-theme-custom.css
=> feat(widget): implementa definições do AnimaliaDS

src/po-theme-custom.css
Cria componente de label, seguindo as regras de estilo do AnimaliaDS
Fixes DTHFUI-6574
=> feat(label): novo componente po-label

package.json
=> build: release v14.8.0

src/po-theme-custom.css
Aplica novo estilo definido pelo design system.
Fixes DTHFUI-6663
=> feat(divider): aplica estilo definido pelo DS

src/po-theme-custom.css
Aplica novo estilo definido pelo design system.
Aplica melhoria de acessibilidade e usabilidade através do contraste das cores e customização de texto.
Fixes DTHFUI-6664
=> feat(tag): aplica estilo definido pelo DS

package.json
=> build: release v14.9.0

package.json
=> build: release v14.9.1

package.json
=> build: release v14.10.0

package.json
=> build: release v14.11.0

src/po-theme-custom.css
refactor(switch): remove variavel --color-switch-color-label
=> refactor(switch): remove variavel --color-switch-color-label

src/po-theme-custom.css
feat(fields): implementa definições do AnimaliaDS
=> feat(fields): implementa definições do AnimaliaDS

src/po-theme-custom.css
=> feat(tooltip): implementa definições do AnimaliaDS

package.json
=> build: release v14.12.0

package.json
=> build: release v14.12.1

package.json
=> build:release v14.12.2

package.json
=> build:release v15.0.0-next.1

src/po-theme-custom.css
DTHFUI-6966 
Corrigido o valor da variável --background-danger-pressed conforme definido no Handoff.
=> fix(button): corrige background-danger-pressed

package.json
=> build: release v15.0.0-rc.0

src/po-theme-custom.css
feat(theme-custom): ajusta fonte alfabeto cirílico
**Simulação**
Rodar portal com theme totvs
=> feat(theme-custom): ajusta fonte alfabeto cirílico

package.json
=> build: release v15.0.0

package.json
=> build: release v15.0.1

package.json
=> build: release v15.1.0

package.json
=> build: release v15.1.1

src/po-theme-custom.css
Cria componente de acordo com as definições de estilo e acessibilidade definidos pelo design system.
Fixes DTHFUI-6733
=> feat(listbox): novo componente

package.json
=> build: release v15.2.0

package.json
=> build: release v15.4.0

package.json
=> build: release v15.5.0

src/po-theme-custom.css
**INPUT**
**fixes DTHFUI-6995**
=> fix(input): ajusta estilização

src/po-theme-custom.css
=> feat(checkbox): implementa definições do AnimaliaDS

package.json
=> build: release v15.6.0

package.json
=> build: release v15.6.1

package.json
=> build: release v15.7.0

package.json
=> build: release v15.8.1

package.json
=> build: release v15.8.2

src/po-theme-custom.css
recebe uma nova propriedade [p-removable] que permite que o componente seja removido.
Fixes DTHFUI-6870
=> feat(tag): implementa novas propriedades

package.json
=> build: release v15.9.0

package.json
=> build: release v15.11.0

package.json
Este PR marca a nova versão 15.12.1 do nosso projeto.
=> build: release v15.12.1

src/po-theme-custom.css
=> feat(menu): implementa definições do AnimaliaDS

package.json
Este PR marca a nova versão v15.13.0 do nosso projeto.
=> build: release v15.13.0

src/po-theme-custom.css
ajusta os token com as customizações do page-slide
fixes DTHFUI-7467
app do po-angular para testar:
[app.zip](https://github.com/totvs/po-theme-totvs/files/12163218/app.zip)
pasta dist do theme-totvs:
[dist.zip](https://github.com/totvs/po-theme-totvs/files/12163233/dist.zip)
=> fix(page-slide): ajusta os tokens do page-slide

src/po-theme-custom.css
Ajusta o token de cor de fundo do page-default
fixes DTHFUI-7467
[app.zip](https://github.com/totvs/po-theme-totvs/files/12164282/app.zip)
=> fix(page-default): ajusta cor de fundo padrão para branco

package.json
Este PR marca a nova versão v15.13.1 do nosso projeto.
=> build: release v15.13.1

package.json
=> build: release v15.14.0

src/po-theme-custom.css
**Implementa campo de busca local no `po-table`**
**Adiciona novo componente interno na biblioteca, `po-search`**
=> feat(search): implementa busca na tabela

package.json
=> build: release v16.0.0-next.0

package.json
=> build: release v16.0.0-next.1

src/po-theme-custom.css
repassa tokens do animaliaDS para uso do `po-dropdown`
Fixes DTHFUI-7634
=> fix(dropdown): repassa tokens do animaliaDS

package.json
=> build: release v16.2.1

src/po-theme-custom.css
implementa definições do AnimaliaDS
=> feat(accordion): implementa definições do AnimaliaDS

package.json
=> build: release 16.3.0

package.json
=> build: release v16.4.0

package.json
=> build: release v16.4.1

package.json
=> build: release v16.5.0

package.json
=> build: release v16.6.0

.github/workflows/publish_ci.yml, package.json
Realiza as correções necessárias para envio do pacote ao npm.
=> DTHFUI-7897 Correção da automação da Release Theme Totvs

package.json
=> build: release v16.6.1

src/po-theme-custom.css
feat(overlay): novo componente de uso interno
DTHFUI-7502
=> feat(overlay): novo componente de uso interno

src/po-theme-custom.css
=> feat(loading-icon): implementa definições do AnimaliaDS

.github/workflows/publish_ci.yml
Realiza a publicação da tag next ao substituir os parâmetros com valores "latest" para os valores "next".
Seguindo as práticas de desenvolvimento de publicação NPM https://docs.npmjs.com/adding-dist-tags-to-packages.
=> fix(publish): Realiza a publicação da tag next

package.json
=> build: release v16.7.0

src/po-theme-custom.css
Atualiza variações light tema Totvs
[app.component.zip](https://github.com/totvs/po-theme-totvs/files/13451280/app.component.zip)
[styles.zip](https://github.com/totvs/po-theme-totvs/files/13451282/styles.zip)
=> feat(theme): atualiza variações light tema Totvs

src/po-theme-custom.css
Implementa modo trigger no componente, ativando a busca via `enter` ou `click` no ícone
fixes DTHFUI-7809
=> feat(search): implementa modo trigger no componente

package.json
=> build: release 16.10.0

src/po-theme-custom.css
implementa definições do AnimaliaDS no componente `po-badge`
Fixes DTHFUI-7933
=> feat(badge): implementa definições do AnimaliaDS

package.json
=> build: release 16.11.0

src/po-theme-custom.css
=> feat(button-group): implementa definições do animaliaDS

src/po-theme-custom.css
Implementa customização via design-tokens definidos pelo AnimaliaDS
Fixes DTHFUI-7910
=> feat(toaster): implementa definições do AnimaliaDS

package.json
=> build: release v16.12.0

package.json
=> build: release v16.13.0

src/po-theme-custom.css
deprecia variáveis de estilo legacy `field-container-bottom`, `field-icon`, `input`.
Fixes DTHFUI-7911
=> refactor(fields): deprecia variaveis de estilo legacy

package.json
=> build: release v16.14.0

src/po-theme-custom.css
Implementação da propriedade de subtitulo
fixes DTHFUI-8292
=> feat(page-default): inclusão do subtitle

package.json
=> build: release v16.15.0

.github/workflows/publish_cd-beta.yml, .github/workflows/publish_cd-latest.yml, .github/workflows/publish_cd-next.yml
Permite publicar no NPM com as tag's: next, latest e beta
Fixes DTHFUI-8079
=> ci: permite publicar no npm com tag especifica

src/index.css
remove importação desnecessária do theme-core.
fixes DTHFUI-8041
=> feat: remove importação theme-core

package.json
=> build: release v17.0.0-next.0

.github/workflows/publish_cd-beta.yml, scripts/update-version.js
Ajusta a publicação na tag @beta do NPM
Fixes DTHFUI-8276
=> ci: ajusta a publicacao da tag @beta

package.json
=> build: release v17.1.1

package.json
=> build: release v17.2.0

package.json
=> build: release v17.3.0

package.json
=> build: release v17.4.0

package.json
=> build: release v17.5.0

src/po-theme-custom.css
Implementação da propriedade "container".
Foi criado um arquivo para o po-dynamic, para ser utilizado tanto para o dynamic-view quanto para o dynamic-form. Adicionado tokens para cores e fonte.
fixes DTHFUI-8252
=> feat(dynamic): inclusão da propriedade container

src/po-theme-custom.css
Adicionado po-combo e po-multiselect no THF-GRID
fixes DTHFUI-8652
=> feat(grid): adiciona `po-combo` e `po-multiselect` na edição em linha

package.json
=> build: release v17.8.0

package.json
=> build: release v17.9.0

package.json
=> release v17.10.0

src/po-theme-custom.css
Adição da propriedade `p-filter-select`, a propriedade define os tipos de filtros (p-filter-keys) a serem aplicados na busca.
fixes DTHFUI-8644
=> feat(search): inclusão da propriedade filterSelect

package.json
=> build: release 17.15.0

package.json
=> build: release 17.15.1

package.json
=> build: release 17.15.2

src/po-theme-custom.css
Criar componente TOASTER e modo `inline` para mostrar componente diretamente no DOM. Componente também é utilizado pelo ‘po-notification’ como modo `alert`
DTHFUI-8864
=> feat(toaster): Criação do componente ‘po-toaster’

package.json
=> build: release v17.18.0

package.json
=> build: release 17.18.1

package.json
=> build: release 17.19.0

package.json
=> build: release 17.20.0

src/po-theme-custom.css
refactor(components): remove variáveis depreciadas
removido tokens que estavam marcados como depreciados.
Fixes DTHFUI-9125
BREAKING CHANGE: removido tokens que estavam marcados como depreciados.
Removido tokens que estavam marcados como depreciados.
=> refactor(components): remove deprecated variables

package.json
=> build: release 17.21.0

package.json
build: release 17.22.0 - DTHFUI-9626
=> build: release 17.22.0 - DTHFUI-9626

package.json
=> build: release 18.7.0

src/po-theme-custom.css
=> feat(stepper): implementa definições do AnimaliaDS

package.json
=> build: release 18.8.0

src/po-theme-custom.css
Implementa definições do animaliaDS no page-slide
fixes DTHFUI-9873
=> feat(page-slide): implementa definições do animalia-DS

package.json
=> build: release 18.11.0

src/po-theme-custom.css
Adicionado propriedade `p-title` e tokens customizados para o titulo em `po-container`
fixes DTHFUI-9918
=> feat(container): adicionado titulo

src/po-theme-custom.css
DTHFUI-9693
Implementa definições Animalia no po-lookup:
Recebe comportamento semelhante do modo trigger do po-search onde possibilita navegar pelo input, realizar consulta, apagar o(s) valor(es) e abrir a modal, pelo teclado.
Mantém o estilo e a customização animalia;
=> feat(lookup): implementa definições animalia-DS

package.json
=> build: release 17.26.7

package.json
=> build: release 18.14.0

package.json
=> build: release 18.17.0

src/po-theme-custom.css
Adicionado possibilidade de passar mais de uma opção de tema de acessibilidade como exemplo: ‘AA’ e ‘AAA’.
Fixes DTHFUI-9037
=> feat(theme): adicionado melhoria no tema para diferentes acessibilidades

package.json
=> build: release 17.26.11

package.json
=> build: release 18.23.1

package.json
=> build: release 17.26.12

package.json
=> build: release 18.24.0

package.json
=> build: release 19.0.0

package.json
=> build: release 19.1.0

package.json
=> build: release 17.26.13

package.json
=> build: release 17.26.18

package.json
=> build: release 19.5.1

src/po-theme-custom.css
- Corrige aplicação da variável `--padding-tabs-header` no `po-page-default`
- Adiciona estilos personalizados para garantir padding correto nos tabs
Fixes DTHFUI-10847
=> feat(tabs): ajusta padding dos po-tabs dentro de po-page-default

src/po-theme-custom.css
**DTHFUI-10108**
_____________________________________________________________________________
**Qual o comportamento atual?**
- Acessibilidade AA reduz a espessura do outline para 2px.
- po-button define o label e ícone como 16px, tanto para o tamanho default quanto para o large.
- po-lookup fica desalinhado com mútiplos valores selecionados.
**Qual o novo comportamento?**
- Acessibilidade AA passa a disponibilizar  (**exceto componentes THF**):
- Uma propriedade de tamanho, para cada componente de formulário e todos os componentes da lib que os utilizam, sendo:
- small: somente quando a acessibilidade for AA
- medium: padrão
- large: permanece apenas para componentes que já o possuem (po-button, po-checkbox, po-radio-group)
- Um método para definir `small` como tamanho padrão dos …
=> feat(components): ajusta buttons e fields conforme acessibilidade

src/po-theme-custom.css
Remove variável de cor não utilizada
- `color-chart-legend-wrapper-scrollbar`.
- `color-chart-line-point-fill`.
- `color-gauge-description-bottom-focus`.
- `color-gauge-legend-scrollbar`.
- `color-gauge-legend-text`.
- `color-gauge-pointer-color`.
Fixes DTHFUI-11334
BREAKING CHANGE: remove variáveis de customização de cores
Remove variáveis para compatibilidade com AnimaliaDS e melhorias de acessibilidade, não sendo mais possível a customização.
- `color-chart-legend-wrapper-scrollbar`
- `color-chart-line-point-fill`
- `color-gauge-description-bottom-focus`
- `color-gauge-legend-scrollbar`
- `color-gauge-legend-text`
- `color-gauge-pointer-color`
=> refactor(chart): remove variáveis não utilizadas

package.json
=> build: release v19.17.0

package.json
=> build: release 17.26.27

package.json
=> build: release 19.20.0

package.json
=> build: release 19.21.0

src/po-theme-custom.css
Cria a classe po-helper responsável por expor variáveis de cor baseadas nos tokens globais, incluindo estados de hover, pressed e disabled, permitindo reaproveitamento de estilos em diferentes contextos.
fixes DTHFUI-11065
=> feat(helper): adiciona classe po-helper com variáveis CSS globais
